version: 0.2

env:
  variables:
    ARTIFACT_BUCKET: demo-cicd-artifacts-<unique>

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Install phase complete"

  build:
    commands:
      - echo "Packaging backend..."
      - tar -czf backend.tar.gz backend

      - echo "Packaging frontend..."
      - tar -czf frontend.tar.gz frontend

      - echo "Uploading to S3..."
      - aws s3 cp backend.tar.gz s3://$ARTIFACT_BUCKET/
      - aws s3 cp frontend.tar.gz s3://$ARTIFACT_BUCKET/

      - echo "Deploy backend via SSM"
      - >
        aws ssm send-command
        --targets "Key=tag:Name,Values=backend-ec2"
        --document-name "AWS-RunShellScript"
        --parameters commands=[
        "aws s3 cp s3://$ARTIFACT_BUCKET/backend.tar.gz /tmp/",
        "tar -xzf /tmp/backend.tar.gz -C /var/www/demoapp --strip-components=1",
        "cd /var/www/demoapp/backend && npm install",
        "systemctl restart demoapp"
        ]

      - echo "Deploy frontend via SSM"
      - >
        aws ssm send-command
        --targets "Key=tag:Name,Values=frontend-ec2"
        --document-name "AWS-RunShellScript"
        --parameters commands=[
        "aws s3 cp s3://$ARTIFACT_BUCKET/frontend.tar.gz /tmp/",
        "tar -xzf /tmp/frontend.tar.gz -C /usr/share/nginx/html --strip-components=1",
        "systemctl reload nginx"
        ]
