version: 0.2

phases:
  build:
    commands:
      - echo "Packaging backend..."
      - tar -czf backend.tar.gz backend

      - echo "Packaging frontend..."
      - tar -czf frontend.tar.gz frontend

      - echo "Upload artifacts to S3..."
      - aws s3 cp backend.tar.gz s3://$ARTIFACT_BUCKET/
      - aws s3 cp frontend.tar.gz s3://$ARTIFACT_BUCKET/

      - echo "Deploy backend via SSM..."
      - |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:Name,Values=backend-ec2" \
          --parameters 'commands=[
            "aws s3 cp s3://'$ARTIFACT_BUCKET'/backend.tar.gz /tmp/",
            "mkdir -p /var/www/demoapp",
            "tar -xzf /tmp/backend.tar.gz -C /var/www/demoapp",
            "cd /var/www/demoapp/backend && npm install",
            "systemctl restart demoapp || node app.js &"
          ]' \
          --no-wait

      - echo "Deploy frontend via SSM..."
      - |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:Name,Values=frontend-ec2" \
          --parameters 'commands=[
            "aws s3 cp s3://'$ARTIFACT_BUCKET'/frontend.tar.gz /tmp/",
            "tar -xzf /tmp/frontend.tar.gz -C /usr/share/nginx/html",
            "systemctl reload nginx"
          ]' \
          --no-wait
